name: Web Scraper Tracker

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'  # This runs every 15 minutes

jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python web_scraper_tracker.py
